/**/*:
  ros__parameters:
    output_directory: "/docker-ros/ws/src/target/ros_graph_exports"
    d2_template_path: ""
    d2_output_filename: "ros_graph.d2"
    export_interval_seconds: 30.0
    export_on_startup: true
    include_hidden_entities: false
    ignore_topics_without_publishers: true
    ignore_topics_without_subscribers: true
