openadservice:
  name: ros2-graph-export
  image: ghcr.io/openads-project/ros2_graph_export:v1.0.0
  env:
    # --- name ------
    NAMESPACE: /
    NAME: ros2_graph_export
    # --- other -----
    EXPORT_GRAPH: ~/export_graph
    LOG_LEVEL: info
    USE_SIM_TIME: false
    PARAMS: /docker-ros/ws/install/ros2_graph_export/share/ros2_graph_export/config/params.yml
  args:
  - /bin/bash
  - -ic
  - |
    ros2 launch ros2_graph_export ros2_graph_export_launch.py \
      namespace:=${NAMESPACE} \
      name:=${NAME} \
      log_level:=${LOG_LEVEL} \
      use_sim_time:=${USE_SIM_TIME} \
      params:=${PARAMS} \
      export_graph:=${EXPORT_GRAPH}
  rosParamFileMountPath: /docker-ros/ws/install/ros2_graph_export/share/ros2_graph_export/config/params.yml
  rosParamFileData: null
